name: Install Kepler SDK on macOS

on:
  workflow_dispatch:

jobs:
  install-kepler-sdk:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install Homebrew
      run: |
        if ! command -v brew &> /dev/null; then
          echo "Homebrew not found. Installing..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        else
          echo "Homebrew is already installed."
        fi

    - name: Authenticate with Kepler Repository
      env:
        CUSTOMER_ID: ${{ secrets.CUSTOMER_ID }}
        KEPLER_TOKEN: ${{ secrets.KEPLER_TOKEN }}
      run: |
        echo "Setting up Kepler credentials..."
        mkdir -p ~/kepler-token-installer
        curl -o kepler-token-script.zip "<URL_DEL_SCRIPT>"  # Reemplazar <URL_DEL_SCRIPT> con la URL correcta
        unzip kepler-token-script.zip -d kepler-token-installer
        cd kepler-token-installer
        chmod +x token-setup.sh
        ./token-setup.sh "$CUSTOMER_ID" "$KEPLER_TOKEN"
        echo "Kepler credentials successfully configured."

    - name: Install Kepler CLI
      run: |
        echo "Installing Kepler CLI..."
        npm install -g @amzn/kepler
        kepler --version

    - name: Install Kepler Platform Tools
      run: |
        echo "Installing Kepler Platform Tools..."
        kepler platform install --force

    - name: Add Kepler Environment Script to .zshrc
      run: |
        echo "Configuring environment script..."
        source ~/.kepler/kntools/sdk/*/environment-setup-sdk.sh
        echo 'source ~/.kepler/kntools/sdk/*/environment-setup-sdk.sh' >> ~/.zshrc

    - name: Verify Installation
      run: |
        echo "Verifying installation..."
        kepler platform doctor
