name: Descargar y subir archivo

on:
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar archivo sin autenticación
      run: |
        curl -L -o archivo.pdf "https://codilamar.com/tienda/pdf/otros-manuales/LD7207.pdf"

    - name: Subir archivo como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: archivo-descargado
        path: archivo.pdf
